### PR TITLE
Add slash nodes for chutney

### PR DESCRIPTION
**Pull request by aagbsn**
Perhaps chutney used to move the old directory rather than symlink?

### CODE REVIEW

**Comment by aagbsn** [comment]
These errors are completely unrelated to bwscanner's own tests and looks like somehow other unit tests are incorrectly being run...

**Review by juga0 — COMMENTED** [review]
I didn't see your PR.
This is the same as https://github.com/TheTorProject/bwscanner/pull/51/commits/55e7eba31fc786342d8420b0412004e4d25864a0

**Review by juga0 — COMMENTED** [review]
Many more changes regarding style: https://github.com/TheTorProject/bwscanner/pull/51/commits/fe45826d6abd9c1d3554d6e2d70fca632ea2ed9a

**Comment by juga0** [comment]
https://github.com/TheTorProject/bwscanner/pull/48, https://github.com/TheTorProject/bwscanner/pull/49, https://github.com/TheTorProject/bwscanner/pull/50 contain the commits from the previous, as https://github.com/TheTorProject/bwscanner/pull/50/commits/51ece834a0cd221714ed5d961f2d37e37747d7e1.
I guess we either remove that commit from https://github.com/TheTorProject/bwscanner/pull/49 and https://github.com/TheTorProject/bwscanner/pull/50 or we can remove previous PRs: https://github.com/TheTorProject/bwscanner/pull/48, https://github.com/TheTorProject/bwscanner/pull/49.

**Review by juga0 — COMMENTED** [review]
I'd leave `requirements.txt` with pinned versions knonw to work and add non-pinned versions or minimal versions known to work to `setup.py`. For instance:

     install_requires=[
        'click', 'pyOpenSSL>=16.2.0', 'service-identity', 'stem', 'Twisted',
        'txsocksx', 'txtorcon'],

**Review by juga0 — COMMENTED** [review]
Indeed, the slash is required to find torrc

**Comment by aagbsn** [comment]
I find that basing PR sequentially means that merge-ff is more likely to work cleanly, though it does imply that PR be merged in-order. I'm not really sure what best practice is, though...

**Comment by hellais** [comment]
> I find that basing PR sequentially means that merge-ff is more likely to work cleanly, though it does imply that PR be merged in-order. I'm not really sure what best practice is, though.

My 0.02$ on this topic is:

If the changes you are making do depend on each other or don't make sense unless the previous PR is merged, yet it makes it easier for the reviewer of them to look at them in isolation (on per PR-basis) as opposed to just inspecting each commit in a big PR, then it makes sense to split them out.

Another reason for doing this is when each pull request affects the same file and so doing separate unrelated PRs would lead to a merge conflict when they land in master.

In other cases it's preferable to either:

* Submit one big pull request with all the changes inside and inform the reviewer that they should look at them on per-commit diff basis
* Make separate pull requests for each change

**Comment by juga0** [comment]
I agree with @hellais, the issue here is that there are separated PRs, but then some contain same commits as others. So, as it is, we can:

a. merge them in order, as @aagbsn comment
b. delete pull/48 and pull/49 and merge only pull/50

In this case, the commits touch separated files and are unrelated to each other, so they should be separated PRs without including the commits in the other. I actually should also separate in different PRs pull/51, specially commit 55e7eba, that is not related to style and turned out to be the same as 51ece83.

In any case, this comment actually comes because i wanted to comment on individual commits but i wasn't sure on which PR. Because i didn't comment directly on the code, the comments on individual commits ended up all here.

To progress on this, i'd merge @aagbsn PRs (either a or b way), but i can't do it because i don't have permissions for it. Then i can update mines and somebody can review them ;)

**Comment by aagbsn** [comment]
closing this request, see other PR (#58 #59)

**Pull request closed without merging**
