### PR TITLE
Style changes

### PR DESCRIPTION
**Pull request by juga0**

### CODE REVIEW

**Comment by aagbsn** [comment]
Can you please rebase this branch into separate pull requests with ideally:

Make code PEP8 compliant fe45826
Add editorconfig 69b9495

Add dev, doc, test requirements and python minimal version fc1b7ce
Add classifiers, license, url 351d14d

**Comment by aagbsn** [comment]
p.s. I'm not sure about the changes to line length. I don't think these changes improve readability and I think somewhere line length is defined as 100 char wide for our style checker tests.

**Comment by juga0** [comment]
> p.s. I'm not sure about the changes to line length. I don't think these changes improve readability and I > think somewhere line length is defined as 100 char wide for our style checker tests.

From https://www.python.org/dev/peps/pep-0008/#maximum-line-length:
> Limit all lines to a maximum of 79 characters.

**Comment by juga0** [comment]
Closing because separated in different PRs, as commented.

**Pull request closed without merging**
