### PR TITLE
Use txtorcon web agent

### PR DESCRIPTION
**Pull request by aagbsn**
Throws out a bunch of code that is now supported by txtorcon directly.

### CODE REVIEW

**Comment by aagbsn** [comment]
This is breaking because I rebased it on top of devel; and tests using hashingReadBody fail because the expected checksum doesn't match expected from the unit tests.

**Comment by juga0** [comment]
With my changes tests are not failing (locally) because hashes don't match, but they fail sometimes because circuits fail:

        assert not failed_measurements
    exceptions.AssertionError

The measurement file contains:

    u'failure': u"<twisted.python.failure.Failure exceptions.Exception: Circuit failed ('CHANNEL_CLOSED')>"

**Comment by juga0** [comment]
I don't know how to reproduce it, but sometimes tests fail locally with:

    Traceback (most recent call last):
      File "/home/user/bwscanner/test/test_writer.py", line 36, in <lambda>
        dl.addCallback(lambda results: walk(self.tmpdir, validate, None))
      File "/home/user/bwscanner/.tox/py27/lib/python2.7/posixpath.py", line 231, in walk
        func(arg, top, names)
      File "/home/user/bwscanner/test/test_writer.py", line 26, in validate
        assert len(fnames) == num_chunks
    exceptions.AssertionError: 

    test.test_writer.TestResultSink.test_send_multiple_chunk_size

**Review by meejah — APPROVED** [review]
Code changes look good to me. I don't know why some circuits are failing -- could it be a Chutney thing? In any case that seems worth investigating.

**Comment by juga0** [comment]
Meged, i'll open other issues after confirming this still happens

**Pull request merged**
